Repository CAPS-DGU/25-1-ClubFair-Server, pull requests merged in 2025-02, with the labels that each got.

#5 [Feature] - 도커 이미지 ECR Push
  .github/workflows/CI_CD.yml
  .github/workflows/PR_check.yml
  Dockerfile
Labels: 🖥️ Deploy, :sparkles: Feature

#8 ✨ [Feature] - 위키 생성 API를 구현한다.
  src/main/java/caps/tf/controller/WikiController.java
  src/main/java/caps/tf/domain/user/User.java
  src/main/java/caps/tf/domain/wiki/ECollege.java
  src/main/java/caps/tf/domain/wiki/EDepartment.java
  src/main/java/caps/tf/domain/wiki/Wiki.java
  src/main/java/caps/tf/dto/wiki/request/CreateWikiRequestDto.java
  src/main/java/caps/tf/exception/WikiErrorCode.java
  src/main/java/caps/tf/repository/WikiRepository.java
  src/main/java/caps/tf/service/user/UserRetriever.java
  src/main/java/caps/tf/service/wiki/WikiSaver.java
  src/main/java/caps/tf/service/wiki/WikiService.java
Labels: :sparkles: Feature

#9 📄 [Docs] - 깃허브 이슈 템플릿과 PR 템플릿을 작성한다.
  .github/ISSUE_TEMPLATE/custom.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 📄 Docs

#17 ✨ [Feature] - 위키 수정 API를 구현한다.
  src/main/java/caps/tf/controller/WikiController.java
  src/main/java/caps/tf/domain/wiki/Wiki.java
  src/main/java/caps/tf/dto/wiki/request/PatchWikiRequestDto.java
  src/main/java/caps/tf/exception/GlobalExceptionHandler.java
  src/main/java/caps/tf/exception/WikiErrorCode.java
  src/main/java/caps/tf/repository/WikiRepository.java
  src/main/java/caps/tf/service/wiki/WikiRetriever.java
  src/main/java/caps/tf/service/wiki/WikiService.java
Labels: :sparkles: Feature
